#questions.py
DEFAULT_QUESTIONS = [
    {'id': 'q1', 'text': 'I value honesty in a partner.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q2', 'text': 'I enjoy staying in rather than going out on a Friday night.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q3', 'text': 'I like planning dates and activities in advance.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q4', 'text': 'Physical fitness and health are important to me.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q5', 'text': 'I enjoy trying new foods and experiences.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q6', 'text': 'I prefer spontaneous activities over planned ones.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q7', 'text': 'I like to communicate frequently with my partner.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q8', 'text': 'I enjoy adventure or risk-taking activities.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q9', 'text': 'I like to spend holidays or vacations actively exploring new places.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q10', 'text': 'I prefer living in a city over a rural area.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q11', 'text': 'I handle stress and challenges calmly and effectively.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q12', 'text': 'I enjoy surprises.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q13', 'text': 'I value spending quality time with friends and family.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q14', 'text': 'I like pets and animals.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q15', 'text': 'I enjoy reading books or articles regularly.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    {'id': 'q16', 'text': 'I enjoy expressing affection openly.', 
     'type': 'multiple-choice', 
     'options': ['Completely disagree', 'Disagree', 'Neutral', 'Agree', 'Completely agree']},
    
    {'id': 'q17', 'text': 'What are some pickup lines you might use?', 'type': 'text'},
    {'id': 'q18', 'text': 'What is your ideal first date?', 'type': 'text'},
    {'id': 'q19', 'text': 'What are your hobbies?', 'type': 'text'},
    {'id': 'q20', 'text': 'How would you ask someone out?', 'type': 'text'},
    {'id': 'q21', 'text': 'Describe your perfect weekend.', 'type': 'text'},
    {'id': 'q22', 'text': 'Describe your favorite movies, shows, or music.', 'type': 'text'},
    {'id': 'q23', 'text': 'Describe your sense of humor.', 'type': 'text'},
    {'id': 'q24', 'text': 'Describe your dream vacation destination.', 'type': 'text'},
    {'id': 'q25', 'text': 'Describe your ideal way to spend a lazy Sunday.', 'type': 'text'}
]
